import shutil
import time
def centrar_texto(texto):

    consola_ancho = shutil.get_terminal_size().columns

    espacios = (consola_ancho - len(texto)) // 2
    texto_centralizado = ' ' * espacios + texto
        
    return texto_centralizado

def primer_dibujo():
    print("")
    print("")
    print("")
    print(centrar_texto(" ______________________________________________________________________ "))
    print(centrar_texto("|: : : : : : : : : : :|_|_|_|_|_|_|_|_|_|_|_||: : : : : : : : : : : : :|"))
    print(centrar_texto("| : : : : : : : : : : ||_|_|_|_|_|_|_|_|_|_|_| : : : : : : : : : : : : |"))
    print(centrar_texto("|: : : : : : : : : : :|_|_|_|_|_|_|_|_|_|_|_||: : : : : : : : : : : : :|"))
    print(centrar_texto("| : : : : : : : : : : ||_|_|_|_|_|_|_|_|_|_|_: : : : : : : : : : : : : |"))
    print(centrar_texto("|: : : : : : : : : : :|_|_|_|_|_|_|_|_|_|_|_||: : : : : : : : : : : : :|"))
    print(centrar_texto("| : :O: : : : : : : : ||_|_|_|_|_|_|_|_|_|_|_| : : : : : : : : : : : : |"))
    print(centrar_texto("|: : :/ \\: : : : : : :|_|_|_|_|_|_|_|_|_|_|_||: : : : : : : :_: : : : :|"))
    print(centrar_texto("| : /___\\: : : : : : ||_|_|_|_|_|_|_|_|_|_|_| : : : : :"))
    print(centrar_texto("/ \: : : : : : : : : : : :|: : : : : : : : : : : : :|"))
    print(centrar_texto("|=====|~| ___=====,;,/________________________\,;,==========[|]========|"))
    print(centrar_texto("|     |~| \_/    ;(;);                        ;(;);          !         |"))
    print(centrar_texto("|    _|_|__|___   =;============================;=                     |"))
    print(centrar_texto("|    | ______ |    [_|_|_]================[_|_|_]    .-------.-------. |"))
    print(centrar_texto("|    ||      ||    [__|__]       `(       [__|__]    |       :       | |"))
    print(centrar_texto("|    ||      ||    [_|_|_] o     ) (    o [_|_|_]    |   *   :   *   | |"))
    print(centrar_texto("|    ||     }||    [__|__] |    ( ) )   | [__|__]    |       :       | |"))
    print(centrar_texto("|    ||      ||    [_|_|_] |---@@@@@@---| [_|_|_]  ()  ______:______() |"))
    print(centrar_texto("|    ||______||    [__|__]/!\ @@@@@@@@ /!\[__|__]  ||_______________|| |"))
    print(centrar_texto("|___/ ______ \__ /______________________________\_||_______________||_|"))
    print(centrar_texto("   |/      \|  |________________________________||| ''            ||"))
    print(centrar_texto("                 .;;;;;;;;;;;;;;;;;;;;;;;;;;;.   ||               ||"))
    print(centrar_texto("                :;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:"))
    print(centrar_texto("                :;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:"))
    print(centrar_texto("                 ':::::::::::::::::::::::::::'"))

def segundoDibujo():
    print("")
    print("")
    print("")
    print("")
    print("")
    print(centrar_texto("              ________"))            
    print(centrar_texto("             / ______ \\"))
    print(centrar_texto("             || _  _ ||"))
    print(centrar_texto("             ||| || |||"))
    print(centrar_texto("             |||_||_|||"))
    print(centrar_texto("                 || _  _o|| (o)"))
    print(centrar_texto("             ||| || |||"))
    print(centrar_texto("                         |||_||_|||      ^~^  ,"))
    print(centrar_texto("                         ||______||     ('Y') )"))
    print(centrar_texto("                        /__________\\    /   \\/"))
    print(centrar_texto("    ________|__________|__ (\\|||/) _________"))
    print(centrar_texto("   hjw     /____________\\"))
    print(centrar_texto("   `97     |____________|"))
    print("")
    print("")
    print("")
    print("")

def tercerDibujo():
    print("")
    print("")
    print(centrar_texto(" __________________________________________________________"))
    print(centrar_texto(" |     ,--.                                                |")          )
    print(centrar_texto(" |    //^\\\\\   ,;;;,                        .            |"))
    print(centrar_texto(" |   ((-_-))) (-_- ;                       /_\\            |"))
    print(centrar_texto(" |    )))(((   >..'.    .:.     .--.      |SSt|            |"))
    print(centrar_texto(" |   ((_._ )  /.   .|  :-_-;   /-_-))                      |"))
    print(centrar_texto(" |   _))A ((_//| S ||  ,`-'.   ))-((                       |"))
    print(centrar_texto(" |   `(    )`' |___|),;, C \\\\_/,`I ))                    |"))
    print(centrar_texto(" |     \  /    | | |`' |___(/-'|___()  ,-.                 | "))
    print(centrar_texto(" |      )(     | | |   | | |   | | |  (-_-)    _____       |"))
    print(centrar_texto(" |     /__\\    |_|_|   |_|_|   |_|_|  (\\I/\\.__|A|R|T|   |"))
    print(centrar_texto(" |     `''     `-'-'   `-'-'   `-'-'  `'-`'   `o' `o'      |"))
    print(centrar_texto(" |___________________Familia Robinson______________________|"))
    print(centrar_texto(" |_________________________1976____________________________|"))
    print(centrar_texto(" |_________________________________________________________|"))
    print("")
    print("")
    print("")


def cuarto_dibujo():
    print("")
    print("")
    print("")
    print("")
    print(centrar_texto("       _.--._  _.--._"))
    print(centrar_texto(",-=.-\":;:;:;\\':;:;:;\"-._"))
    print(centrar_texto("\\\\\\:;:;:;:;:;\\:;:;:;:;:;\\"))
    print(centrar_texto(" \\\\\\:;:;:;:;:;\\:;:;:;:;:;\\"))
    print(centrar_texto("  \\\\\\:;:;:;:;:;\\:;:;:;:;:;\\"))
    print(centrar_texto("   \\\\\\:;:;:;:;:;\\:;::;:;:;:\\"))
    print(centrar_texto("    \\\\\\;:;::;:;:;\\:;:;:;::;:\\"))
    print(centrar_texto("     \\\\\\;;:;:_:--:\\:_:--:_;:;\\    "))
    print(centrar_texto("      \\\\\\_.-\"      :      \"-._\\"))
    print(centrar_texto("       \\`_..--\"\"--.;.--\"\"--.._= >"))
    print(centrar_texto("        \"")  )
    print("")
    print("")
    print("")
    print("")
    print("")

def quinto_dibujo():
    print(centrar_texto("   _______________  []         _________________"))
    print(centrar_texto("   _______________) []        (_______________"))
    print(centrar_texto("    !     !     !   []        '  !     !     !"))
    print(centrar_texto("    !     !     !   []       ,!  !     !     !"))
    print(centrar_texto("    !     !     !   []      ! !  !     !     !"))
    print(centrar_texto("    !_____!_____!___[]_____'!_!__!_____!_____!_____"))
    print(centrar_texto("                    []__,_!_!_!"))
    print(centrar_texto("                    []_!__!_!|"))
    print(centrar_texto("                   ,[]_!__!_!"))
    print(centrar_texto("                 ,! []_!__!|"))
    print(centrar_texto("               ,! ! []_!__!"))
    print(centrar_texto("              ! ! ! []_!|"))
    print(centrar_texto("             !! ! !|[]_|"))
    print(centrar_texto("             !!!._|_[]"))
    print(centrar_texto("             !!!|!_.[]"))
    print(centrar_texto("             !|!_!__[]!."))
    print(centrar_texto("             !_!_!__[]! !."))
    print(centrar_texto("             !_!_!__[]! ! `."))
    print(centrar_texto("              |!_!__|]! ! ! `."))
    print(centrar_texto("               |_!__|]! ! ! ! `."))
    print(centrar_texto("                 |____|_! ! ! !  `"))
    print(centrar_texto("                   |____|_! ! !"))
    print(centrar_texto("                    []____|_! !"))
    print(centrar_texto("                    []______|_!"))
    print(centrar_texto("                    []________|_!"))
    print(centrar_texto("  __________________[]__________|____________________"))

def sexto_dibujo():
    print( centrar_texto("        _________________________"))
    print( centrar_texto("       (, ______________________ )"))
    print( centrar_texto("       | |                      ||"))
    print(centrar_texto( "       | |          @@@@        ||            @@@@"))
    print( centrar_texto("       | |        @@@@@@@       ||          @@@@@@@"))
    print( centrar_texto("       | |         @@ - -       ||          - @@@@"))
    print( centrar_texto("       | |          @  c/       ||         '_ @@@"))
    print( centrar_texto("       | |        _@| |_        ||         __\@ \@"))
    print(centrar_texto( "       | |       ( \ )/_\ /_    ||  _\\  (/ ) @\_/)"))
    print( centrar_texto("       | |        \ \|) / \)    ||   |(__/ /     /|"))
    print( centrar_texto("       | |        |\_/ ( -/     ||    \___/ ----/_|"))
    print( centrar_texto("       | |        /     \       ||       ,:   '("))
    print( centrar_texto("       | |       :    _/|       ||       |:     \\"))
    print( centrar_texto("       | |       :      |       ||       |:      )"))
    print( centrar_texto("       | |       :      |       ||       |:      |"))
    print(centrar_texto( "       | |_______'____,_|_______||       |_____,_|"))
    print( centrar_texto("   .---('________________________)--.     |   / ("))
    print( centrar_texto("   |____          __________       _|     |  /\  )"))
    print( centrar_texto("    |___|   -o-  |       |__|  -o- |      (  \| /"))
    print(centrar_texto( "    |___|   -o-  |       |__|  -o- |      |  /'=. "))
    print( centrar_texto("   |________|       |__|______|      '=>/  \\"))
    print(centrar_texto("                                         /  \\ /|/"))
    print( centrar_texto("                                       ,___/|") )


def septimo_dibujo():
    print( centrar_texto("     8 8 8 8                     ,ooo."))
    print( centrar_texto("     8a8 8a8                    oP   ?b"))
    print( centrar_texto("    d888a888zzzzzzzzzzzzzzzzzzzz8     8b"))
    print( centrar_texto("     `\"\"^\"\"'                    ?o___oP'"))
    print(centrar_texto( " __"))
    print(centrar_texto("              /o \_____"))
    print(centrar_texto( "              \__/-=\"=\"`"))
    print( centrar_texto("            __"))
    print(centrar_texto( "           / o\\"))
    print( centrar_texto("           \_ /"))
    print( centrar_texto("            <|"))
    print(centrar_texto( "            <|"))
    print(centrar_texto( "     jgs    <|"))
    print( centrar_texto("            `") )

def octavo_dibujo():
    print(  centrar_texto(" __________________________________________________________________"))
    print(  centrar_texto("/ \\-----     ---------  -----------     -------------- ------    ----\\"))
    print(centrar_texto( "\\_/__________________________________________________________________/"))
    print( centrar_texto( "|~ ~~ ~~~ ~ ~ ~~~ ~ _____.----------._ ~~~  ~~~~ ~~   ~~  ~~~~~ ~~~~|"))
    print(centrar_texto( "|  _   ~~ ~~ __,---'_       \"         `. ~~~ _,--.  ~~~~ __,---.  ~~|"))
    print(  centrar_texto("| | \\___ ~~ /      ( )   \"          \"   `-.,' (') \\~~ ~ (  / _\\ \\~~ |"))
    print(  centrar_texto("|  \\    \\__/_   __(( _)_      (    \"   \"     (_\\_) \\___~ `-.___,'  ~|"))
    print( centrar_texto("|~~ \\     (  )_(__)_|( ))  \"   ))          \"   |    \"  \\ ~~ ~~~ _ ~~|"))
    print(  centrar_texto("|  ~ \\__ (( _( (  ))  ) _)    ((     \\\\//    \" |   \"    \\_____,' | ~|"))
    print( centrar_texto( "|~~ ~   \\  ( ))(_)(_)_)|  \"    ))    //\\\\ \" __,---._  \"  \"   \"  /~~~|"))
    print( centrar_texto("|    ~~~ |(_ _)| | |   |   \"  (   \"      ,-'^~~~ ~~~ `-.   ___  /~ ~ |"))
    print( centrar_texto( "| ~~     |  |  |   |   _,--- ,--. _  \"  (~   ~~~~  ~~~ ) /___\\ \\~~ ~|"))
    print(centrar_texto( "|  ~ ~~ /   |      _,----._,'`--'\\.`-._  `._~~_~__~_,-'  |H__|  \\ ~~|"))
    print(  centrar_texto("|~~    / \"     _,-' / `\\ ,' / _'  \\`.---.._          __        \" \\~ |"))
    print(centrar_texto(  "| ~~~ / /   .-' , / ' _,'_  -  _ '- _`._ `.`-._    _/- `--.   \" \" \\~|"))
    print( centrar_texto( "|  ~ / / _-- `---,~.-' __   --  _,---.  `-._   _,-'- / ` \\ \\_   \" |~|"))
    print( centrar_texto( "| ~ | | -- _    /~/  `-_- _  _,' '  \\ \\_`-._,-'  / --   \\  - \\_   / |"))
    print( centrar_texto( "|~~ | \\ -      /~~| \"     ,-'_ /-  `_ ._`._`-...._____...._,--'  /~~|"))
    print( centrar_texto( "| ~~\\  \\_ /   /~~/    ___  `---  ---  - - ' ,--.     ___        |~ ~|"))
    print( centrar_texto( "|~   \\      ,'~~|  \" (o o)   \"         \" \" |~~~ \\_,-' ~ `.     ,'~~ |"))
    print( centrar_texto( "| ~~ ~|__,-'~~~~~\\    \\\"/      \"  \"   \"    /~ ~~   O ~ ~~`-.__/~ ~~~|"))
    print( centrar_texto( "|~~~ ~~~  ~~~~~~~~`.______________________/ ~~~    |   ~~~ ~~ ~ ~~~~|"))
    print( centrar_texto( "|____~_____~__~_______~~_~____~~_____~~___~_~~___~\\_|_/ ~_____~___~__|"))
    print( centrar_texto( "/ \\----- ----- ------------  ------- ----- -------  --------  -------\\"))
    print( centrar_texto( "\\_/__________________________________________________________________/") )


def noveno_dibujo():
    print( centrar_texto( "                                    _______________________      |"))
    print( centrar_texto( "                                  |  ________   ________  |     |"))
    print( centrar_texto("                                  | |        | |    ___ | |     |"))
    print(centrar_texto( "                                  | |        | |  ,',.('| |     |"))
    print( centrar_texto("                                  | |        | | :  .'  | |     |"))
    print( centrar_texto("                                  | |        | | :) _  (| |     |"))
    print( centrar_texto("                                  | |        | |  `:_)_,| |     |"))
    print(centrar_texto( "                                  | |________| |________| |     |"))
    print(centrar_texto( "                                  |  ________   ________  |     |"))
    print(centrar_texto( "                                  | |        | |        | |     |"))
    print( centrar_texto("                                  | |        | |        | |     |"))
    print(centrar_texto( "                                  | |        | |        | |     |"))
    print( centrar_texto("                                  | |        | |        | |     |"))
    print( centrar_texto( "                                  | |        | |        | |     |"))
    print( centrar_texto("                                  | |________| |________| |     |"))
    print( centrar_texto("                                  |_______________________|     |"))
    print( centrar_texto("                                                                |"))
    print( centrar_texto("                                                                |"))
    print( centrar_texto("                   _____________________________________________|"))
    print( centrar_texto("                                                                `."))
    print(centrar_texto( "                                                                  `."))
    print(centrar_texto( "                                                                    `."))
    print(centrar_texto( "                                                                      `."))
    print( centrar_texto("                     ..::::::::::::' .:::::::::::::::                   `."))
    print( centrar_texto("                 ..:::::::::::::::' .:::::::::::::::'                     `"))
    print(centrar_texto( "             ..:::::::::::::::::' .:::::::::::::::::"))


def decimo_dibujo():
    print( centrar_texto("      _________      "))
    print( centrar_texto("     /\ ()()()/\           (^)"))
    print( centrar_texto("    /  \_\\_\\_\\__\         {(o)}"))
    print(centrar_texto( "    \  /\        \         \O/"))
    print( centrar_texto("     \/::\   dos  \          v"))
    print(centrar_texto( "      \:::\ patitos\       ,---@"))
    print(centrar_texto( "       \:::\        \      | . |_"))
    print(centrar_texto( "        \:::\        \     |____7"))
    print(centrar_texto( "         \:::\________\    |    |"))
    print(centrar_texto( "          \::/        /    |    |"))
    print(centrar_texto( "           \/________/     |    |"))
    print( centrar_texto("                           |    |"))
    print( centrar_texto("                           |    |"))
    print( centrar_texto("                           |____|"))

def  onceava_decision():
    print(centrar_texto("         ___         _______________________________      .-."))
    print(centrar_texto("      |                               |               .'   `."))
    print(centrar_texto("      |                               |               :g g   :"))
    print(centrar_texto("      |                               |               : o    `."))
    print(centrar_texto("      |   .|,        ,'drx.           |              :         ``."))
    print(centrar_texto("      |  -(_)-      |::|888L          |             :             `."))
    print(centrar_texto("      |   '|`       ;:::8888L         |            :  :         .   `."))
    print(centrar_texto("      |            ;::::Y8888L        |            :   :          ` . `."))
    print(centrar_texto("      |------------|::::|88888L-------|             `.. :            `. ``;"))
    print(centrar_texto("      |            ;:::::888888L      |                `:;             `:'"))
    print(centrar_texto("      |           ;::::::Y888888L     |                   :              `."))
    print(centrar_texto("      |           |::::::|888888'L.   |    jgs            `.              `."))
    print(centrar_texto("      |           `-::::::888F'MMMML. |                     `'`'`'`---..,___`;.-'"))
    print(centrar_texto("      |               `-::F'MMMMMMMMML|"))
    print(centrar_texto("      |                   `\"**MMMMMMMM|"))
    print(centrar_texto("      |                          `\"**M|"))
    print(centrar_texto("      |                               |"))
    print(centrar_texto("      |                               |"))
    print(centrar_texto("      |    .;                         |"))
    print(centrar_texto("      |                               |"))
    print(centrar_texto("      |                               |"))
    print(centrar_texto("      |_______________________________|"))


def dibujo_detective():
    print( centrar_texto("              ,;;;,"))
    print( centrar_texto("             ;;;;;;;"))
    print(centrar_texto( "          .-'`\, '/_"))
    print(centrar_texto( "        .'   \ (\"`(_)"))
    print(centrar_texto( "       / `-,.'\ \_/"))
    print(centrar_texto( "       \  \/\\  `--`"))
    print(centrar_texto( "        \  \ \ "))
    print(centrar_texto( "         / /| |"))
    print(centrar_texto( "        /_/ |_|"))
    print(centrar_texto( "  jgs  ( _\ ( _\  #:##        #:##        #:##         #:##"))
    print(centrar_texto( "                        #:##        #:##        #:##"))


def fin():
       
        print( centrar_texto( "$$$$$$$$\       "))
        print( centrar_texto("$$  _____|      "))
        print( centrar_texto( "$$ |            "))
        print( centrar_texto( "$$$$$\          "))
        print(  centrar_texto("$$  __|         "))
        print(  centrar_texto("$$ |            "))
        print( centrar_texto( "$$ |            "))
        print(  centrar_texto("\__|            "))
        print( centrar_texto( "                "))
        print( centrar_texto( "                "))
        time.sleep(1)
        print( centrar_texto("$$\\ "))
        print(centrar_texto( "\\__|"))
        print(centrar_texto( "$$\\ "))
        print(centrar_texto( "$$ |"))
        print( centrar_texto("$$ |"))
        print( centrar_texto("$$ |"))
        print( centrar_texto("$$ |"))
        print( centrar_texto("\\__|"))
        print("    ")
        print("    ")
        time.sleep(1)
        print(centrar_texto("$$\\   $$\\ "))
        print(centrar_texto("$$$\\  $$ |"))
        print(centrar_texto("$$$$\\ $$ |"))
        print(centrar_texto("$$ $$\\$$ |"))
        print(centrar_texto("$$ \\$$$$ |"))
        print(centrar_texto("$$ |\\$$$ |"))
        print(centrar_texto("$$ | \\$$ |"))
        print(centrar_texto("\\__|  \\__|"))
        print("           ")
        print("           ")

def dibujo_introduccion():
    print( centrar_texto("                              ___   .            ___.'       '.   *"))
    print( centrar_texto("        .              _____[LLL]______________[LLL]_____     \\"))
    print( centrar_texto("                      /     [LLL]              [LLL]     \     |"))
    print( centrar_texto("                     /____________________________________\    |    ."))
    print( centrar_texto("                      )==================================(    /"))
    print( centrar_texto("     .      *         '|I .-. I .-. I .--. I .-. I .-. I|'  .'"))
    print( centrar_texto("                  *    |I |+| I |+| I |. | I |+| I |+| I|-'`       *"))
    print( centrar_texto("                       |I_|+|_I_|+|_I_|__|_I_|+|_I_|+|_I|      ."))
    print( centrar_texto("              .       /_I_____I_____I______I_____I_____I_\""))
    print( centrar_texto("                       )================================(   *"))
    print( centrar_texto("       *         _     |I .-. I .-. I .--. I .-. I .-. I|          *"))
    print( centrar_texto("                |u|  __|I |+| I |+| I |<>| I |+| I |+| I|    _         ."))
    print( centrar_texto("           __   |u|_|uu|I |+| I |+| I |~ | I |+| I |+| I| _ |U|     _"))
    print( centrar_texto("       .  |uu|__|u|u|u,|I_|+|_I_|+|_I_|__|_I_|+|_I_|+|_I||n|| |____|u|"))
    print( centrar_texto("          |uu|uu|_,.-' /I_____I_____I______I_____I_____I\`'-. |uu u|u|__"))
    print( centrar_texto("          |uu.-'`      #############(______)#############    `'-. u|u|uu|"))

   
    print( centrar_texto("  ~'^'~    _,'~'^'~    _( )_                         _( )_   `'-.        ~'^'~"))
    print( centrar_texto("      _  .'            |___|                         |___|      ~'^'~     _"))
    print( centrar_texto("    _( )_              |_|_|          () ()          |_|_|              _( )_"))
    print( centrar_texto("    |___|/\/\/\/\/\/\/\|___|/\/\/\/\/\|| ||/\/\/\/\/\|___|/\/\/\/\/\/\/\|___|"))
    print( centrar_texto("    |_|_|\/\/\/\/\/\/\/|_|_|\/\/\/\/\/|| ||\/\/\/\/\/|_|_|\/\/\/\/\/\/\/|_|_|"))
    print( centrar_texto("    |___|/\/\/\/\/\/\/\|___|/\/\/\/\/\|| ||/\/\/\/\/\|___|/\/\/\/\/\/\/\|___|"))
    print( centrar_texto("    |_|_|\/\/\/\/\/\/\/|_|_|\/\/\/\/\/[===]\/\/\/\/\/|_|_|\/\/\/\/\/\/\/|_|_|"))
    print( centrar_texto("    |___|/\/\/\/\/\/\/\|___|/\/\/\/\/\|| ||/\/\/\/\/\|___|/\/\/\/\/\/\/\|___|"))
    print( centrar_texto("~'^'~|_|_|\/\/\/\/\/\/\/|_|_|\/\/\/\/\/|| ||\/\/\/\/\/|_|_|\/\/\/\/\/\/\/|_lc|~'^'~"))
    print( centrar_texto("   [_____]            [_____]                       [_____]            [_____] ") )



def bienvenida():
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print(centrar_texto("/$$$$$$$  /$$$$$$ /$$$$$$$$ /$$   /$$ /$$    /$$ /$$$$$$$$ /$$   /$$ /$$$$$$ /$$$$$$$   /$$$$$$"))                          
    print(centrar_texto("| $$__  $$|_  $$_/| $$_____/| $$$ | $1$| $$   | $$| $$_____/| $$$ | $$|_  $$_/| $$__  $$ /$$__  $$"))
    print(centrar_texto("| $$  \ $$  | $$  | $$      | $$$$| $$| $$   | $$| $$      | $$$$| $$  | $$  | $$  \ $$| $$  \ $$"))
    print(centrar_texto("| $$$$$$$   | $$  | $$$$$   | $$ $$ $$|  $$ / $$/| $$$$$   | $$ $$ $$  | $$  | $$  | $$| $$  | $$"))
    print(centrar_texto("| $$__  $$  | $$  | $$__/   | $$  $$$$ \  $$ $$/ | $$__/   | $$  $$$$  | $$  | $$  | $$| $$  | $$"))
    print(centrar_texto("| $$  \ $$  | $$  | $$      | $$\  $$$  \  $$$/  | $$      | $$\  $$$  | $$  | $$  | $$| $$  | $$"))
    print(centrar_texto("| $$$$$$$/ /$$$$$$| $$$$$$$$| $$ \  $$   \  $/   | $$$$$$$$| $$ \  $$ /$$$$$$| $$$$$$$/|  $$$$$$/"))
    print(centrar_texto("|_______/ |______/|________/|__/  \__/    \_/    |________/|__/  \__/|______/|_______/  \______/"))
    print("")
    print("")
    print("")
    print("")
    print("")


def fantasmita():
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(centrar_texto("                   _.-,"))
    print(centrar_texto("              _ .-'  / .._"))
    print(centrar_texto("           .-:'/ - - \\:::::-."))
    print(centrar_texto("         .::: '  e e  ' '-::::."))
    print(centrar_texto("        ::::'(    ^    )_.::::::"))
    print(centrar_texto("       ::::.' '.  o   '.::::'.'/_"))
    print(centrar_texto("   .  :::.'       -  .::::'_   _.:"))
    print(centrar_texto(" .-''---' .'|      .::::'   '''::::"))
    print(centrar_texto("'. ..-:::'  |    .::::'        ::::"))
    print(centrar_texto(" '.' ::::    \\ .::::'          ::::"))
    print(centrar_texto("      ::::   .::::'           ::::"))
    print(centrar_texto("       ::::.::::'._          ::::"))
    print(centrar_texto("        ::::::' /  '-      .::::"))
    print(centrar_texto("         '::::-/__    __.-::::'")     )
    print(centrar_texto("           '-::::::::::::::-'"))
    print(centrar_texto("                '''::::'''"))
    print(" ")
    print(" ")
    pass

def menu():
    print(centrar_texto("     ,---.           ,---."))
    print(centrar_texto("    / /\"`.\\.--\"\"\"--./,'\"\\ \\"))
    print(centrar_texto("    \\ \\    _       _    / /"))
    print(centrar_texto("     `./  / __   __ \\  \\,'"))
    print(centrar_texto("      /    /_O)_(_O\\    \\"))
    print(centrar_texto("      |  .-'  ___  `-.  |"))
    print(centrar_texto("   .--|       \\_/       |--."))
    print(centrar_texto(" ,'    \\   \\   |   /   /    `."))
    print(centrar_texto("/       `.  `--^--'  ,'       \\"))
    print(centrar_texto(".-\"\"\"\"\"\"-.    `--.___.--'     .-\"\"\"\"\"\"-."))
    print(centrar_texto("| .---------\\         /----------------- \\         /------------. |"))
    print(centrar_texto("| |          `-`--`--'                    `--'--'-'             | |"))
    print(centrar_texto("| |                                                             | |"))
    print(centrar_texto("| |                                                             | |"))
    print(centrar_texto("| |                      1- COMENZAR                           | |"))
    print(centrar_texto("| |                                                             | |"))
    print(centrar_texto("| |                                                             | |"))
    print(centrar_texto("| |                                                             | |"))
    print(centrar_texto("| |                         2- SALIR                            | |"))
    print(centrar_texto("| |                                                             | |"))
    print(centrar_texto("| |                                                             | |"))
    print(centrar_texto("| |                                                             | |"))
    print(centrar_texto("| |                                                             | |"))
    print(centrar_texto("| |                                                             | |"))
    print(centrar_texto("| |_____________________________________________________________| |"))
    print(centrar_texto("|_________________________________________________________________|"))
    print(centrar_texto("  )__________|__|__________("))
    print(centrar_texto(" |            ||            |"))
    print(centrar_texto(" |____________||____________|"))
    print(centrar_texto("   ),-----.(      ),-----.("))
    print(centrar_texto(" ,'   ==.   \\    /  .==    `."))
    print(centrar_texto("/            )  (            \\"))
    print(centrar_texto("`==========='    `==========='"))
    

def espia():
        print( centrar_texto("              ,;;;,"))
        print( centrar_texto("             ;;;;;;;"))
        print(centrar_texto( "          .-'`\, '/_"))
        print(centrar_texto( "        .'   \ (\"`(_)"))
        print(centrar_texto( "       / `-,.'\ \_/"))
        print(centrar_texto( "       \  \/\\  `--`"))
        print(centrar_texto( "        \  \ \ "))
        print(centrar_texto( "         / /| |"))
        print(centrar_texto( "        /_/ |_|"))
        print(centrar_texto( "  jgs  ( _\ ( _\  #:##        #:##        #:##         #:##"))
        print(centrar_texto( "                        #:##        #:##        #:##"))